### ISSUE TITLE
Add contributor License agreement assistant

### ISSUE THREAD

**Issue by security-companion** [w4af/w4af#239]
I've seen on other repos a Contributor license agreement check on pull requests.
I think it would be good to also have this on this repo to handle the legal side of commits.
see https://github.com/cla-assistant/cla-assistant

**Comment by codders** [comment]
Not a huge fan of these - see some of the arguments here: https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/

I think I prefer to take the risk onto us as a project, and not force individual contributors to make any extra legal agreements.

**Comment by security-companion** [comment]
okay, I understand. I'll close this issue then.
