### ISSUE TITLE
Replace content in code and docu: w3af by w4af

### ISSUE THREAD

**Issue by security-companion** [w4af/w4af#256]

**Comment by security-companion** [comment]
most of the work is done. There are only some minor changes that are necessary left.

**Comment by codders** [comment]
Do you have an overview of what is left here?

**Comment by security-companion** [comment]
I went again through all the code to check where "w3af" was found. Most findings are references to issues on the old repo which I would leave like that.
Some findings are tests that seem to access w3af.org, I need we need to leave that for the moment as our homepage currently is just a redirect to readthedocs and therefore changing that probably will break the tests.

Then I found 3 times w3af in w4af\plugins\tests\crawl\test_import_results.py and I'm not sure about these. Actually I was thinking that they should now fail as we are now using w4af-moth which I was expecting to have the folder w4af in it and therefore eg. http://127.0.0.1:8000/w3af/file_upload/ should not exist and fail the test.
Perhaps you can correct/advise me on that.
Once we clarify this file we can close this issue.

**Comment by codders** [comment]
The tests in `test_import_results.py` run against the `moth` environment, which is based on `w4af/django-moth`. I haven't renamed everything in that project, and there are a bunch of references to `w3af` in there. I'll take a look at fixing that shortly.

**Comment by codders** [comment]
Okay. It turns out that this test was loading scan results from a base64-encoded file the still contained a reference to a w3af scan result. I've now updated that in #443 - once that's merged I'll close this.

**Comment by security-companion** [comment]
Thank you very much for looking into this.
