### ISSUE TITLE
Update docker file in w4af/extras/docker

### ISSUE THREAD

**Issue by security-companion** [w4af/w4af#259]
The docker file in w4af/extras/docker needs to be reviewed/updated.
Once we have a webclient it would be good to also expose its port to outside of the docker container.

**Comment by security-companion** [comment]
we should also decide when is the proper moment to add w4af to docker hub

**Comment by codders** [comment]
Working on this in #325

**Comment by security-companion** [comment]
@codders: Thank you very much for working on this.
I saw that at the end, the w4af_console is started.
I've been wondering. How would I do to start the webclient-gui automatically once the docker image loads/runs? (the respective port would also then needed to being published to the outside world so that I can access the GUI from a browser that is not inside of the docker-container)
Or should we make a separate docker image for this?

**Comment by codders** [comment]
Hi @security-companion ,

Right now, you can pass arguments directly to the docker container to run another one of the scripts, for example:

````
docker run -it w4af/w4af:latest w4af_console -h
```
or
```
docker run -it w4af/w4af:latest w4af_gui
```
or
```
docker run -it w4af/w4af:latest w4af_api
```

For me, for now, that is enough flexibility. The GUI essentially doesn't exist right now, and the API fails with the dependency check code (see #335). I would focus on just having the console working well for the alpha release and say anything else is 'nice to have'

**Comment by security-companion** [comment]
Thanks for your feedback.
With the way that you show for executing other command when starting the container it is fine for me with leaving it like that.
Okay, then let's focus on the console for now and the rest later.
