### ISSUE TITLE
Decide and update documentation related to which operating system and python versions we currently support

### ISSUE THREAD

**Issue by security-companion** [w4af/w4af#260]
eg. which is the last ubuntu version we support?

**Comment by security-companion** [comment]
My suggestion would be to support respective to ubuntu only the last LTS version. Not sure about other OS (CentOS).
Might be it would be good to support again kali and perhaps ParrotOS as those are the distros used by most pentesters.

**Comment by codders** [comment]
I wonder, once we get rid of the GTK dependencies, whether we can run as a pure python project. Most of the distro compatibility is about installing the native packages.

**Comment by codders** [comment]
No - you're correct. That's also my understanding. If we can be pure python, we don't need the dependency check.

The only thing I'm not sure is whether we will need some system -dev libraries installed so that platform-dependent pip packages can be installed if a suitable "wheel" isn't available.

**Comment by codders** [comment]
I've removed the GUI code in #306. The tests now pass on the stock `ubuntu-latest` github runner image. Since I am only running on Linux, and the CI is only running on `ubuntu-latest`, I would say supported platforms right now are Ubuntu-22.04 and nothing else. But since it's a pure python project now, I expect it shouldn't be too hard to make it a bit portable. Just the question how we test that - I don't have experience with the Mac and Windows runners.

**Comment by security-companion** [comment]
It seems to be possible to also run github actions on Windows and MacOS:
`matrix:

os: [ubuntu-latest, macos-latest, windows-latest]`
excerpt from [https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python, section ](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python)

We could even build an exe-file/installer for windows that brings everything (right python version, w4af-code and all dependencies) that is necessary to run. I've seen this eg. on the [youtube-dl site](http://ytdl-org.github.io/youtube-dl/)

Although I feel that this is not something for alpha release but for a later stage. I think that almost all pentesters that want to try w4af have access to a linux machine.

Also we need to consider if we start running tests also on other platforms we increase our build-time and at some stage run out of free minutes.

**Comment by codders** [comment]
I think it's okay to just drop the support for the other platforms for now - I have no real excitement for developing for Mac or Windows. We just need to be aware that our cross-platform compatibility will suffer in the long-run if we're not testing for it.

**Comment by security-companion** [comment]
I agree that more platforms means more testing effort or frustrated users if we do not test.
If I remember well Windows is already marked as not supported in the docu. I'll update docu for Mac that is is not supported neither.

**Comment by codders** [comment]
Perfect. Thank you.

**Comment by security-companion** [comment]
Docu is adapted, see commit f32638134

**Comment by codders** [comment]
Fixed in #346
