### ISSUE TITLE
Add contributors-guideline

### ISSUE THREAD

**Issue by security-companion** [w4af/w4af#278]
It would be good to have a contributors guideline.
see eg the one from [ruby on rails](https://github.com/rails/rails/blob/main/CONTRIBUTING.md) as a suggestion

**Comment by codders** [comment]
This seems good - I'm happy if you want to add that in. I would also like to have a contributor code-of-conduct - I like this one: https://www.contributor-covenant.org/version/2/0/code_of_conduct/

**Comment by security-companion** [comment]
Thanks, I've shortend it a but as some items (like templates for issues and how to submit security issues) we do not yet have.
I also added a code of conduct.
What we still need to define is a contact address for the code of conduct.

**Comment by codders** [comment]
Sounds good. I don't know what address to use - do you get any e-mail forwarding with the w4af.net address?

btw - it would be good to cancel the test run if you're only making small readme changes - right now the test suite is quite resource intensive!

**Comment by security-companion** [comment]
Good idea, I created mail at w4af.net and will add that to the guideline.
Okay, sorry, I'll cancel the test next time
