### ISSUE TITLE
result-file in root

### ISSUE THREAD

**Issue by security-companion** [w4af/w4af#298]
@codders: There's a result-file in root that is empty. Do you think this is still needed or can it be deleted?

**Comment by codders** [comment]
Looking at the git log, it seems to be a file left over from when @andresriancho moved the project to github. It's an empty file - I'm pretty sure it can go :)

**Comment by andresriancho** [comment]
👋 

it can go 👍 :-)

**Comment by codders** [comment]
That'll be gone with #306
