### ISSUE TITLE
Question about error_handlers.py

### ISSUE THREAD

**Issue by security-companion** [w4af/w4af#300]
I was updating links from the old to the new repo and found
new_issue = 'https://github.com/andresriancho/w3af/issues/new'
in
/w4af/w4af/core/ui/api/resources/error_handlers.py

Is this currently active?
If I change it to the new repo will we then get many automatically created issues once the software crashes on a user machine?

**Comment by codders** [comment]
The code that is definitely active and is tested every test suite execution is the code in `w4af/core/controllers/easy_contribution/github_issues.py`, and that already points to the w4af/w4af repo.

I see there is code in `w4af/core/ui/gui/exception_handling/unhandled_bug_report.py` that references the old repo, but we are going to delete the GUI code. And there is the code you reference in `w4af/w4af/core/ui/api/resources/error_handlers.py`, that appears to be triggered if there is a 500 error coming out of the `w4af_api`.

So far, there is no test for that (as far as I can see). I think it's good if you can update that to point at the correct repo, but from what I can see it doesn't automatically file any bug. It just puts the link to the issue URL in the JSON error response for the user to read.

**Comment by security-companion** [comment]
Okay, thanks. I'll updated it and it will show up with my next git push

**Comment by security-companion** [comment]
see commit hash 6a5a4d9bf
