### ISSUE TITLE
Suggestion: make w4af_console, w4af_gui and w4af_api more similar

### ISSUE THREAD

**Issue by security-companion** [w4af/w4af#335]
Hi,
I looked at w4af_console, w4af_gui and w4af_api. In kdiff3 I saw that they have some code that is equal but over time also they got code that diverged.
My idea/question is if we should not try to make them a bit more equal to get somehow the same behaviour.

Some differences I found:
* The w4af_api does not have a dependency_check, w4af_gui does have it enabled by default, and w4af_console has it disabled by default
* First line with #! is different
* Command line options are not the same, I know that the different script have different purposes and therefore also have different options. But perhaps help and version should be available in all the 3 files.

@codders: If you agree in general on my suggestion I could start working on a branch and then we could use this branch as base for discussions.

**Comment by codders** [comment]
Hi @security-companion ,

Yes - there is a lot of duplication there and not a lot of difference in functionality. I feel like we will eventually get to the place of having just two scripts - the `w4af_console` script for interactive terminal sessions, and a `w4af_server` script for API and GUI sessions. The GUI is anyway now a static website that is served by the API server.

As I wrote in #338, I think we could probably drop the `dependency_check` from all of them - maybe that's another pull request just to remove the mechanism entirely.

For `w4af_console`, the #! is important - the console requires unbuffered IO on stdout and stdin to function correctly in an interactive session. If you want to remove the `python -u` switch there, you will need to change the `w4af_console` switch to change stdin/stdout to unbuffered at runtime (which is anyway maybe a better idea than relying on the #!).

**Comment by codders** [comment]
And yes, if you want to start working on a branch for any of these changes, that would be most welcome :)

**Comment by security-companion** [comment]
@codders:
I've started working on a branch now.
As we've decided to keep focus on the console for our alpha-release I thought that perhaps in w4af_api and w4f_gui we should bring a message on startup that says something like: "This is still experimental, please use the w4af_console command instead. If you want to use it anyhow hand over param --testing". Something like you did with the "--i-am-a-developer" param you made the other day.
Otherwise people might start opening up bugs regarding to why w4af_api and w4af_gui still show little functionality.
What do you think?

**Comment by security-companion** [comment]
Branch can be found here: https://github.com/w4af/w4af/tree/start-script-command-params

**Comment by codders** [comment]
I think it's a good idea to have a warning on the `w4af_gui` script. The `ẁ4af_api` script should be working (as far as I know) and is covered by unit tests, so if someone wants to report bugs there I think it would be good to hear from them.

**Comment by codders** [comment]
I rebased your branch to bring it a bit more up-to-date. Do you have any more concrete idea about what you would like to see here? If I add the 'i-am-a-developer' flag to w4af_api and w4af_gui, would that meet your requirements for this ticket?

**Comment by security-companion** [comment]
Thanks for rebasing.
Yes, for me it would be okay to add a "i-am-a-developer" flag on w4af_api and w4af_gui (and add a hint about this in the help parameter output) and then we could merge the branch and close this issue.

**Comment by codders** [comment]
This should be addressed in #495
