### ISSUE TITLE
tags from old w3af project

### ISSUE THREAD

**Issue by security-companion** [w4af/w4af#361]
Hi,
I found that this repo project lists tags (eg. 1.6), see https://github.com/w4af/w4af/tags
I think if we start with 1.0.0-alpha1 for our first alpha-release or later use also 1.6 as release for w4af this might get confusing.
Should we remove the old tags from the w3af-team?
I would opt to do so to start again from scratch with version numbering.
What do you thinkg?

**Comment by codders** [comment]
Yes - please remove the old tags. I think they will just be confusing

**Comment by security-companion** [comment]
okay, I've removed them now.
