### ISSUE TITLE
Unable to pull docker image

### ISSUE THREAD

**Issue by ChenliangEdward** [w4af/w4af#363]
I tried first docker login and ran
`sudo docker run -it w4af/w4af:latest`
and it shows 
```
docker: Error response from daemon: pull access denied for w4af/w4af, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
I went to your Dockerhub and did not see your w4af/w4af image.
Any help will be appreciated.

**Comment by rohit-rambade** [comment]
I think w4af/w4af repository is not available on the docker hub 
w4af/w4af-moth is the correct name I guess 
try this  
`docker pull w4af/w4af-moth`

**Comment by codders** [comment]
`w4af-moth` is an image used by the test suite - it is not the image you
are looking for.

I'm not sure where `w4af` went, but I will push it again in some hours.

How did you become aware of the project? We are very happy for the
interest, and we are still in early phases with our alpha release :)

Rohit Rambade ***@***.***> schrieb am Fr., 3. Feb. 2023,
06:22:

**Comment by codders** [comment]
Should be there now - https://hub.docker.com/r/w4af/w4af

You might be our first users - experience reports are very welcome. As I said, the project is in pre-alpha release (see https://github.com/w4af/w4af/milestone/1 ), so we don't offer any warranty just yet :)

**Comment by ChenliangEdward** [comment]
I can pull it without any problem. Thank you so much!!!
