### ISSUE TITLE
I get a lot of errors when runing w4af.The following error was displayed when install darts ,i tried switching  python version to install again, but it didn't work out either.

### ISSUE THREAD

**Issue by kijzahdlkw** [w4af/w4af#585]
error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-l__c7q5m/numba_26024c754e06454b8739583cb6efb88f/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/tmp/pip-install-l__c7q5m/numba_26024c754e06454b8739583cb6efb88f/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.2; only versions >=3.7,<3.11 are supported.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by kijzahdlkw** [comment]
When I run w4af, it shows that I have some modules that I don't, I installed them, but with each installation another one appears, and even some modules prevent me from installing

**Comment by codders** [comment]
Hi @kijzahdlkw ,

Thanks for the report. Are you using `pipenv` to install the dependencies?

**Comment by kijzahdlkw** [comment]
Hi @codders 

I using pip3 to install these dependencies

**Comment by codders** [comment]
You need to use `pipenv` to install the dependencies, per the readme.
