### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement darts-util-lru==0.5.1

### ISSUE THREAD

**Issue by Mettthew** [w4af/w4af#593]
Hello everyone, this is my first time to make a ticket, I hope I didn't do anything wrong in requesting it.

I am trying to install in my Kali Linux virtual machine w4af to test it, but after doing the installation following the guide found in the documentation and running from terminal the command "./w4af_api", what appears is the following error:

Your python installation needs the following modules to run w4af: darts.lib.utils 
After installing any missing operating system packages, use pip to install the remaining modules:
 sudo pip install darts-util-lru==0.5.1
A script with these commands has been created for you at /tmp/w4af_dependency_install.sh

before only pointing me to this missing dependency, there were others but I installed all of them, for this last remaining one when I try to install it with the command "sudo pip3 install darts-util-lru==0.5.1" it gives me the following problem:

ERROR: Could not find a version that satisfies the requirement darts-util-lru==0.5.1 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5)                                                                                                                     
ERROR: No matching distribution found for darts-util-lru==0.5.1 

it seems that this version of this module does not exist at all.
I tried to install the latest version of this module (0.5), but the error still persists, Also, when I run the command "pip3 freeze | grep darts-util-lru" it returns nothing, while if I run the same command but with "." instead of the "-", it returns version 0.5 (I'm pointing this out to you in case it might be important as a problem), do you happen to know how to solve this problem?

**Comment by Mettthew** [comment]
thank you very much for your answer, I tried what you suggested right away but it gives me the following answer:


sudo pipenv install darts-util-lru==0.5.1

Creating a virtualenv for this project...
Pipfile: /home/kali/w4af/Pipfile
Using /usr/bin/python3 (3.11.4) to create virtualenv...
⠧ Creating virtual environment...created virtual environment CPython3.11.4.final.0-64 in 425ms
  creator CPython3Posix(dest=/root/.local/share/virtualenvs/w4af-XvBe1O5H, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==23.2, setuptools==66.1.1, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /root/.local/share/virtualenvs/w4af-XvBe1O5H
Installing darts-util-lru==0.5.1...
Resolving darts-util-lru==0.5.1...
Adding darts-util-lru to Pipfile's [packages] ...
✔ Installation Succeeded
Pipfile.lock (0e5612) out of date, updating to (01e36f)...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
Resolving dependencies...
✘ Locking Failed!
⠇ Locking...
CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement darts-util-lru==0.5.1 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5)
[ResolutionFailure]:   File "/usr/lib/python3/dist-packages/pipenv/resolver.py", line 704, in _main
[ResolutionFailure]:       resolve_packages(
[ResolutionFailure]:   File "/usr/lib/python3/dist-packages/pipenv/resolver.py", line 662, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:       ^^^^^^^^
[ResolutionFailure]:   File "/usr/lib/python3/dist-packages/pipenv/resolver.py", line 642, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:       ^^^^^^^^^^^^^
[ResolutionFailure]:   File "/usr/lib/python3/dist-packages/pipenv/utils/resolver.py", line 1167, in resolve_deps
[ResolutionFailure]:       results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
[ResolutionFailure]:       ^^^^^^^^^^^^^^^^^^^^^^
[ResolutionFailure]:   File "/usr/lib/python3/dist-packages/pipenv/utils/resolver.py", line 948, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/usr/lib/python3/dist-packages/pipenv/utils/resolver.py", line 690, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv run pip install <requirement_name> to bypass this mechanism, then run $ pipenv graph to inspect the versions actually installed in the virtualenv.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: No matching distribution found for darts-util-lru==0.5.1


maybe the solution is simple, but I still don't understand much about these things, What should I do now?

**Comment by codders** [comment]
He @Mettthew ,

You should not be running `sudo pipenv install darts-util-lru==0.5.1`. The `Pipfile` provided with the project contains all the dependencies already.

Please checkout the project into a new folder, and just run:

`pipenv install`

in the fresh checkout to install the dependencies. Then run `pipenv shell` in that same folder to enter the `pipenv` environment for the project.

**Comment by Mettthew** [comment]
seems to be working now, thank you very much for everything :) sorry for that stupid question, but I had missed that passage while reading the installation, now i have to study how API works :D

**Comment by codders** [comment]
Great - happy to hear it!
