### ISSUE TITLE
How to set profiles for using API

### ISSUE THREAD

**Issue by Mettthew** [w4af/w4af#613]
Excuse me for another question but I'm trying to use the api offered by w4af to run a scan, reading the documentation however it is not clear to me how to specify the profile I should send to start the scan.

I tried creating a profile from the w4af_console, but when I save it with "save_as name self-contained", I can't find the file saved in the "profiles" folder.

Any advice?

**Comment by codders** [comment]
Hi @Mettthew ,

Probably worth you taking a look at #592 - someone there had a similar question.

**Comment by Mettthew** [comment]
I try to run this script in Python using the Profile example that i found online:

"import requests
import json

data = {'scan_profile':   "[profile]\n\nname = scan\n\n[grep.strange_headers]\n\n[crawl.web_spider]\nonly_forward = True\nfollow_regex = .*\nignore_regex = \n\n",
        'target_urls': [MY_URL']}

response = requests.post('http://127.0.0.1:5000/scans/',
                         data=json.dumps(data),
                         headers={'content-type': 'application/json'})"


When I run it what is printed is right:

"<Response [201]>
{'href': '/scans/0', 'id': 0, 'message': 'Success'}
0"


But when I try to connect to the endpoint "http://127.0.0.1:5000/scans/0" where 0 is the scan id, it returns the following json:

{"code":405, "message": "Method not allowed"}


And I don't know what to do to make it work

**Comment by codders** [comment]
Hi @Mettthew ,

Looks like you're making some progress! Sorry it's a bit of a pain in the ass. I had a go myself based on the code you provided - here is a gist of my attempt: https://gist.github.com/codders/7c8fbfbfb6d6e726c3d388b7882b26fb

There's a couple of things to note. For me, the API is running over HTTPS, so I have to use HTTPS in the API URL and pass the `verify=False` argument to `requests`.

Second, looking at the API code for the `scans` REST resource, there is no `GET` method on a Scan, which is why you get the 405 error:
https://github.com/w4af/w4af/blob/main/w4af/core/ui/api/resources/scans.py

What I did find was a `GET` method for the scan logs:
https://github.com/w4af/w4af/blob/main/w4af/core/ui/api/resources/log.py

which allows you to make a request of the form `/scans/<id>/log` and get the log output. If you check out the `resources` folder in the API code you should see other REST objects and their URLs.

Hope that helps!

**Comment by Mettthew** [comment]
Thank you very much for the clarification, checking again well the main problem I was able to solve, it was so stupid, but I thought I wrote it the right way, that is, to get the status I had to add the endpoint "/status" to the one I was already using, and now it actually works!

The only thing I now need to figure out is how to write the profile I want to use in the correct way. 

As suggested in the documentation I would like to enable all plugins, all grep and finally crawl.web_spider with the settings I already indicated, but I don't really know how to do it.

**Comment by codders** [comment]
Hi @Mettthew ,

There are a bunch of example profiles in the `profiles` folder of the project. Maybe you can use one of those as a reference?

**Comment by Mettthew** [comment]
@codders thank you so much for the support, eventually I was able to figure out how to create a profile and manually entered everything I needed and created one to use in my scanning, if it is helpful to you I created the following profile that takes into account all audits, all grep and finally craw_spider with Only_forward = True and I did it in the following way:

`scan_profile':   "[profile]\n\nname = scan\n\n[audit.file_upload]\nextensions = gif,html\n\n[audit.eval]\nuse_time_delay = True\nuse_echo = True\n\n[audit.un_ssl]\n\n[audit.os_commanding]\n\n[audit.lfi]\n\n[audit.sqli]\n\n[audit.preg_replace]\n\n[audit.phishing_vector]\n\n[audit.generic]\ndiff_ratio = 0.35\nextensive = False\n\n[audit.format_string]\n\n[audit.ldapi]\n\n[audit.buffer_overflow]\n\n[audit.redos]\n\n[audit.global_redirect]\n\n[audit.xpath]\n\n[audit.xss]\npersistent_xss = True\n\n[audit.htaccess_methods]\n\n[audit.dav]\n\n[audit.ssi]\n\n[audit.csrf]\n\n[audit.ssl_certificate]\nmin_expire_days = 30\nca_file_name = %(ROOT_PATH)s/plugins/audit/ssl_certificate/ca.pem\n\n[audit.xst]\n\n[audit.blind_sqli]\neq_limit = 0.9\n\n[audit.mx_injection]\n\n[audit.response_splitting]\n\n[audit.rfi]\nlisten_address = \nlisten_port = 44449\nuse_w4af_site = True\n\n[audit.frontpage]\n\n[audit.deserialization]\n\n[audit.memcachei]\n\n[audit.rfd]\n\n[audit.shell_shock]\n\n[audit.websocket_hijacking]\n\n[audit.xxe]\n\n[audit.cors_origin]\norigin_header_value = http://w4af.net/\n\n[grep.analyze_cookies]\n\n[grep.blank_body]\n\n[grep.cache_control]\n\n[grep.cdn_providers]\n\n[grep.clamav]\nclamd_socket = /var/run/clamav/clamd.ctl\n\n[grep.click_jacking]\n\n[grep.code_disclosure]\n\n[grep.content_sniffing]\n\n[grep.credit_cards]\n\n[grep.cross_domain_js]\nsecure_js_file = w4af/plugins/grep/cross_domain_js/secure-js-sources.txt\n\n[grep.csp]\n\n[grep.directory_indexing]\n\n[grep.dom_xss]\n\n[grep.dot_net_event_validation]\n\n[grep.error_500]\n\n[grep.error_pages]\n\n[grep.expect_ct]\n\n[grep.feeds]\n\n[grep.file_upload]\n\n[grep.form_autocomplete]\n\n[grep.form_cleartext_password]\n\n[grep.get_emails]\nonly_target_domain = True\n\n[grep.hash_analysis]\n\n[grep.html_comments]\n\n[grep·http_auth_detect]\n\n[grep.http_in_body]\n\n[grep.keys]\n\n[grep.lang]\n\n[grep.meta_generator]\n\n[grep.meta_tags]\n\n[grep.motw]\n\n[grep.objects]\n\n[grep.oracle]\n\n[grep.password_profiling]\n\n[grep.path_disclosure]\n\n[grep.private_ip]\n\n[grep.retirejs]\nretire_db_url = https://raw.githubusercontent.com/RetireJS/retire.js/master/repository/jsrepository.json\n\n[grep.serialized_object]\n\n[grep.ssn]\n\n[grep.strange_headers]\n\n[grep.strange_http_codes]\n\n[grep.strange_parameters]\n\n[grep.strange_reason]\n\n[grep.strict_transport_security]\n\n[grep.svn_users]\n\n[grep.symfony]\noverride = False\n\n[grep.url_session]\n\n[grep.user_defined_regex]\nsingle_regex = \nregex_file_path = w4af/plugins/grep/user_defined_regex/empty.txt\n\n[grep.vulners_db]\nvulners_api_key = None\n\n[grep.websockets_links]\n\n[grep.wsdl_greper]\n\n[grep.xss_protection_header]\n\n[crawl.web_spider]\nonly_forward = True\nfollow_regex = .*\nignore_regex = \n\n"`

I have tried to specify for each plugin the default settings of their required elements, I seem to have set them correctly for all of them, but in case if there is any error please let me know, I hope maybe this scan profile can be useful to others who like me at the beginning have a bit of a struggle to understand them

**Comment by codders** [comment]
Hi @Mettthew ,

Happy to hear you've made some progress here. If you have time or interest, it would be great if you could write up your experience and learnings in the form of a document that other users could refer to. The API functionality is still in `alpha`, and `w4af` is always happy to have collaborators.

If you consider the issue resolved, please also close the ticket.

Thanks!

**Comment by Mettthew** [comment]
I would love to cooperate,

but unfortunately at this time I don't have much time, I have to prepare my university thesis for graduation, but in the future if I can I will definitely let you know, thanks again for all the support :) (maybe in a little while I might as well ask more questions)
