### ISSUE TITLE
Explanation of vulnerability fields appearing in the report

### ISSUE THREAD

**Issue by Mettthew** [w4af/w4af#643]
### Discussed in https://github.com/w4af/w4af/discussions/641

<div type='discussions-op-text'>

<sup>Originally posted by **Mettthew** September  8, 2023</sup>
hello everyone,

I wanted to ask if by any chance there was any documentation where all the possible fields that appear when searching for a specific vulnerability found through the endpoint `"http://127.0.0.1:5000/scans/scan_id/kb/id"` are explained one by one.

- for example, I know that the `cwe_ids` and `wasc_ids` fields refer to the `Common Weakness Enumeration` and `Web Application Security Consortium`, respectively, while `VulnDB_id` I imagine refers to a Vulnerabilities Database but I don't understand which one specifically, because searching the Web one can find several.
- Another question that comes to mind is what `Uniq_id` refers to.
- and lastly is ` owasp_top_10_references` valid to consider or have they been updated? because I've noticed that the `Owasp version` that appears is `2013` and the link that is generally associated with it doesn't actually lead to what it should indicate, for example: `"owasp_top_10_references":[{"link":"https://www.owasp.org/index.php/Top_10_2013-A1","owasp_version":"2013","risk_id":1}]`

There are also other fields that I don't quite understand, but these are the main ones for now.</div>

**Comment by Mettthew** [comment]
thank you very much for the reply! just the last things and then i think i understood almost everything :)

- What do these fields mean?` Attributes, Highlight, Urls, Var`

I checked in the file you pointed me to and it seems to me that there is no detailed description of what they are (or maybe I checked it wrong) and I would need something like that to understand better.

Let's say that these fields are not critical to what I should be doing, however since I should be using several scanners for my university thesis I should try to specify things as correctly as possible

**Comment by codders** [comment]
Hi @Mettthew,

I don't know exactly what ends up in `Attributes`, but it looks like some additional properties of the vulnerability discovered. `Highlight` relates to vulnerabilities discovered by string matching - the highlight is the part of the string that matched. `Urls` is every Url associated with this vulnerability. And `Var` is the variable / parameter that was used for injection / fuzzing if it is an injection / fuzzing vulnerability.

Would be really interested to hear more about your thesis when you have something to share - please feel free to ask any additional questions you might have.

**Comment by Mettthew** [comment]
**I really thank you very much for all the information you gave me!**

For my thesis, the task they gave me is to consider several scanners, use them against the same target, and combine their outputs

These are the first times I have gotten my hands on tools like these and it is not very easy for me xD If I come up with more questions later, I will definitely ask them :D
