### ISSUE TITLE
AttributeError: 'SynchronizedLRUDict' object has no attribute 'values'

### ISSUE THREAD

**Issue by jcpentester** [w4af/w4af#678]
Faced errors in running the w4af after installing the dependencies and still encountering missing modules required.

Below is the error I've encountered.

┌──(venv)─(kali㉿kali)-[~/Downloads/tools/w4af]
└─$ ./w4af_console
It seems that your Python installation does not have all the modules required by the w4af framework. For more information about how to install and debug dependency issues please browse to http://docs.w4af.net/en/latest/install.html
Exception ignored in atexit callback: <function cleanup_pool at 0x7ffbb412e660>
Traceback (most recent call last):
  File "/home/kali/Downloads/tools/w4af/w4af/core/data/parsers/parser_cache.py", line 392, in cleanup_pool
    dpc.clear(ignore_errors=True)
  File "/home/kali/Downloads/tools/w4af/w4af/core/data/parsers/parser_cache.py", line 92, in clear
    for parser in self._cache.values():
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'SynchronizedLRUDict' object has no attribute 'values'

**Comment by codders** [comment]
Hi there,

Did you use Pipenv to install the dependencies?

Thanks,

Arthur

jcpentester ***@***.***> schrieb am Di., 19. Sept. 2023,
08:46:

**Comment by jcpentester** [comment]
Hi Codders, I've tried following the guide but encountered the error below using the "pipenv" command.

The result is shown below:
──(w4af-TkbCYEsO)─(kali㉿kali)-[~/Downloads/tools/w4af]
└─$ pipenv install     
Installing dependencies from Pipfile.lock (0e5612)...
[pipenv.exceptions.InstallError]: Collecting apispec==6.0.2 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 1))
[pipenv.exceptions.InstallError]:   Using cached apispec-6.0.2-py3-none-any.whl (29 kB)
[pipenv.exceptions.InstallError]: Collecting apispec-webframeworks==0.5.2 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 2))
[pipenv.exceptions.InstallError]:   Using cached apispec_webframeworks-0.5.2-py2.py3-none-any.whl (12 kB)
[pipenv.exceptions.InstallError]: Collecting arrow==1.2.3 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 3))
[pipenv.exceptions.InstallError]:   Using cached arrow-1.2.3-py3-none-any.whl (66 kB)
[pipenv.exceptions.InstallError]: Collecting attrs==22.2.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 4))
[pipenv.exceptions.InstallError]:   Using cached attrs-22.2.0-py3-none-any.whl (60 kB)
[pipenv.exceptions.InstallError]: Collecting beautifulsoup4==4.11.2 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 5))
[pipenv.exceptions.InstallError]:   Using cached beautifulsoup4-4.11.2-py3-none-any.whl (129 kB)
[pipenv.exceptions.InstallError]: Collecting blinker==1.5 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 6))
[pipenv.exceptions.InstallError]:   Using cached blinker-1.5-py2.py3-none-any.whl (12 kB)
[pipenv.exceptions.InstallError]: Collecting bravado-core==5.17.1 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 7))
[pipenv.exceptions.InstallError]:   Using cached bravado_core-5.17.1-py2.py3-none-any.whl (67 kB)
[pipenv.exceptions.InstallError]: Collecting certifi==2022.12.7 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 8))
[pipenv.exceptions.InstallError]:   Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
[pipenv.exceptions.InstallError]: Collecting chardet==5.1.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 9))
[pipenv.exceptions.InstallError]:   Using cached chardet-5.1.0-py3-none-any.whl (199 kB)
[pipenv.exceptions.InstallError]: Collecting charset-normalizer==3.0.1 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 10))
[pipenv.exceptions.InstallError]:   Using cached charset_normalizer-3.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (196 kB)
[pipenv.exceptions.InstallError]: Collecting click==8.1.3 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 11))
[pipenv.exceptions.InstallError]:   Using cached click-8.1.3-py3-none-any.whl (96 kB)
[pipenv.exceptions.InstallError]: Collecting cluster==1.4.1.post3 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 12))
[pipenv.exceptions.InstallError]:   Using cached cluster-1.4.1.post3-py2.py3-none-any.whl (28 kB)
[pipenv.exceptions.InstallError]: Collecting colorama==0.4.6 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 13))
[pipenv.exceptions.InstallError]:   Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
[pipenv.exceptions.InstallError]: Collecting configargparse==1.5.3 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 14))
[pipenv.exceptions.InstallError]:   Using cached ConfigArgParse-1.5.3-py3-none-any.whl (20 kB)
[pipenv.exceptions.InstallError]: Collecting configparser==5.3.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 15))
[pipenv.exceptions.InstallError]:   Using cached configparser-5.3.0-py3-none-any.whl (19 kB)
[pipenv.exceptions.InstallError]: Collecting cryptography==38.0.4 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 16))
[pipenv.exceptions.InstallError]:   Using cached cryptography-38.0.4-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
[pipenv.exceptions.InstallError]: Collecting defusedxml==0.7.1 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 17))
[pipenv.exceptions.InstallError]:   Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
[pipenv.exceptions.InstallError]: Collecting deprecated==1.2.13 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 18))
[pipenv.exceptions.InstallError]:   Using cached Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
[pipenv.exceptions.InstallError]: Collecting diff-match-patch==20200713 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 19))
[pipenv.exceptions.InstallError]:   Using cached diff_match_patch-20200713-py3-none-any.whl (61 kB)
[pipenv.exceptions.InstallError]: Collecting ds-store==1.3.1 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 20))
[pipenv.exceptions.InstallError]:   Using cached ds_store-1.3.1-py3-none-any.whl (16 kB)
[pipenv.exceptions.InstallError]: Collecting filelock==3.9.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 21))
[pipenv.exceptions.InstallError]:   Using cached filelock-3.9.0-py3-none-any.whl (9.7 kB)
[pipenv.exceptions.InstallError]: Collecting flask==2.2.3 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 22))
[pipenv.exceptions.InstallError]:   Using cached Flask-2.2.3-py3-none-any.whl (101 kB)
[pipenv.exceptions.InstallError]: Collecting fqdn==1.5.1 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 23))
[pipenv.exceptions.InstallError]:   Using cached fqdn-1.5.1-py3-none-any.whl (9.1 kB)
[pipenv.exceptions.InstallError]: Collecting future==0.18.3 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 24))
[pipenv.exceptions.InstallError]:   Using cached future-0.18.3.tar.gz (840 kB)
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'done'
[pipenv.exceptions.InstallError]: Collecting gitpython==3.1.31 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 25))
[pipenv.exceptions.InstallError]:   Using cached GitPython-3.1.31-py3-none-any.whl (184 kB)
[pipenv.exceptions.InstallError]: Collecting hpack==4.0.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 26))
[pipenv.exceptions.InstallError]:   Using cached hpack-4.0.0-py3-none-any.whl (32 kB)
[pipenv.exceptions.InstallError]: Collecting html2text==2020.1.16 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 27))
[pipenv.exceptions.InstallError]:   Using cached html2text-2020.1.16-py3-none-any.whl (32 kB)
[pipenv.exceptions.InstallError]: Collecting hyperscan==0.4.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 28))
[pipenv.exceptions.InstallError]:   Using cached hyperscan-0.4.0-cp311-cp311-manylinux_2_24_x86_64.whl (4.9 MB)
[pipenv.exceptions.InstallError]: Collecting ipaddresses==0.0.2 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 29))
[pipenv.exceptions.InstallError]:   Using cached ipaddresses-0.0.2-py2.py3-none-any.whl (360 kB)
[pipenv.exceptions.InstallError]: Collecting isoduration==20.11.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 30))
[pipenv.exceptions.InstallError]:   Using cached isoduration-20.11.0-py3-none-any.whl (11 kB)
[pipenv.exceptions.InstallError]: Collecting itsdangerous==2.1.2 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 31))
[pipenv.exceptions.InstallError]:   Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
[pipenv.exceptions.InstallError]: Collecting jellyfish==0.9.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 32))
[pipenv.exceptions.InstallError]:   Using cached jellyfish-0.9.0.tar.gz (132 kB)
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'done'
[pipenv.exceptions.InstallError]: Collecting joblib==1.2.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 33))
[pipenv.exceptions.InstallError]:   Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
[pipenv.exceptions.InstallError]: Collecting jsonpointer==2.3 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 34))
[pipenv.exceptions.InstallError]:   Using cached jsonpointer-2.3-py2.py3-none-any.whl (7.8 kB)
[pipenv.exceptions.InstallError]: Collecting jsonref==1.1.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 35))
[pipenv.exceptions.InstallError]:   Using cached jsonref-1.1.0-py3-none-any.whl (9.4 kB)
[pipenv.exceptions.InstallError]: Collecting jsonschema[format]==4.17.3 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 36))
[pipenv.exceptions.InstallError]:   Using cached jsonschema-4.17.3-py3-none-any.whl (90 kB)
[pipenv.exceptions.InstallError]: Collecting lxml==4.9.2 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 37))
[pipenv.exceptions.InstallError]:   Using cached lxml-4.9.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.2 MB)
[pipenv.exceptions.InstallError]: Collecting lz4==4.3.2 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 38))
[pipenv.exceptions.InstallError]:   Using cached lz4-4.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
[pipenv.exceptions.InstallError]: Collecting mac-alias==2.2.2 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 39))
[pipenv.exceptions.InstallError]:   Using cached mac_alias-2.2.2-py3-none-any.whl (21 kB)
[pipenv.exceptions.InstallError]: Collecting mailbits==0.2.1 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 40))
[pipenv.exceptions.InstallError]:   Using cached mailbits-0.2.1-py3-none-any.whl (11 kB)
[pipenv.exceptions.InstallError]: Collecting markdown==3.4.1 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 41))
[pipenv.exceptions.InstallError]:   Using cached Markdown-3.4.1-py3-none-any.whl (93 kB)
[pipenv.exceptions.InstallError]: Collecting markupsafe==2.1.2 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 42))
[pipenv.exceptions.InstallError]:   Using cached MarkupSafe-2.1.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (27 kB)
[pipenv.exceptions.InstallError]: Collecting marshmallow==3.19.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 43))
[pipenv.exceptions.InstallError]:   Using cached marshmallow-3.19.0-py3-none-any.whl (49 kB)
[pipenv.exceptions.InstallError]: Collecting memory-profiler==0.61.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 44))
[pipenv.exceptions.InstallError]:   Using cached memory_profiler-0.61.0-py3-none-any.whl (31 kB)
[pipenv.exceptions.InstallError]: Collecting morfessor==2.0.6 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 45))
[pipenv.exceptions.InstallError]:   Using cached Morfessor-2.0.6-py3-none-any.whl (35 kB)
[pipenv.exceptions.InstallError]: Collecting msgpack==1.0.4 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 46))
[pipenv.exceptions.InstallError]:   Using cached msgpack-1.0.4.tar.gz (128 kB)
[pipenv.exceptions.InstallError]:   Installing build dependencies: started
[pipenv.exceptions.InstallError]:   Installing build dependencies: finished with status 'done'
[pipenv.exceptions.InstallError]:   Getting requirements to build wheel: started
[pipenv.exceptions.InstallError]:   Getting requirements to build wheel: finished with status 'done'
[pipenv.exceptions.InstallError]:   Installing backend dependencies: started
[pipenv.exceptions.InstallError]:   Installing backend dependencies: finished with status 'done'
[pipenv.exceptions.InstallError]:   Preparing metadata (pyproject.toml): started
[pipenv.exceptions.InstallError]:   Preparing metadata (pyproject.toml): finished with status 'done'
[pipenv.exceptions.InstallError]: Collecting ndg-httpsclient==0.5.1 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 47))
[pipenv.exceptions.InstallError]:   Using cached ndg_httpsclient-0.5.1-py3-none-any.whl (34 kB)
[pipenv.exceptions.InstallError]: Collecting nltk==3.8.1 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 48))
[pipenv.exceptions.InstallError]:   Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
[pipenv.exceptions.InstallError]: Collecting nocasedict==2.0.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 49))
[pipenv.exceptions.InstallError]:   Using cached nocasedict-2.0.0-py2.py3-none-any.whl (23 kB)
[pipenv.exceptions.InstallError]: Collecting numpy==1.24.2 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 50))
[pipenv.exceptions.InstallError]:   Using cached numpy-1.24.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[pipenv.exceptions.InstallError]: Collecting packaging==23.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 51))
[pipenv.exceptions.InstallError]:   Using cached packaging-23.0-py3-none-any.whl (42 kB)
[pipenv.exceptions.InstallError]: Collecting passlib==1.7.4 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 52))
[pipenv.exceptions.InstallError]:   Using cached passlib-1.7.4-py2.py3-none-any.whl (525 kB)
[pipenv.exceptions.InstallError]: Collecting pbr==5.11.1 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 53))
[pipenv.exceptions.InstallError]:   Using cached pbr-5.11.1-py2.py3-none-any.whl (112 kB)
[pipenv.exceptions.InstallError]: Collecting phply==1.2.6 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 54))
[pipenv.exceptions.InstallError]:   Using cached phply-1.2.6-py2.py3-none-any.whl (74 kB)
[pipenv.exceptions.InstallError]: Collecting pillow==9.4.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 55))
[pipenv.exceptions.InstallError]:   Using cached Pillow-9.4.0-cp311-cp311-manylinux_2_28_x86_64.whl (3.4 MB)
[pipenv.exceptions.InstallError]: Collecting ply==3.11 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 56))
[pipenv.exceptions.InstallError]:   Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
[pipenv.exceptions.InstallError]: Collecting polyglot==16.7.4 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 57))
[pipenv.exceptions.InstallError]:   Using cached polyglot-16.7.4.tar.gz (126 kB)
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'done'
[pipenv.exceptions.InstallError]: Collecting psutil==5.9.4 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 58))
[pipenv.exceptions.InstallError]:   Using cached psutil-5.9.4-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)
[pipenv.exceptions.InstallError]: Collecting pyahocorasick==2.0.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 59))
[pipenv.exceptions.InstallError]:   Using cached pyahocorasick-2.0.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (118 kB)
[pipenv.exceptions.InstallError]: Collecting pyasn1==0.4.8 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 60))
[pipenv.exceptions.InstallError]:   Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
[pipenv.exceptions.InstallError]: Collecting pyclamd==0.4.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 61))
[pipenv.exceptions.InstallError]:   Using cached pyClamd-0.4.0.tar.gz (11 kB)
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'done'
[pipenv.exceptions.InstallError]: Collecting pycld2==0.41 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 62))
[pipenv.exceptions.InstallError]:   Using cached pycld2-0.41.tar.gz (41.4 MB)
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'done'
[pipenv.exceptions.InstallError]: Collecting pycryptodome==3.17 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 63))
[pipenv.exceptions.InstallError]:   Using cached pycryptodome-3.17-cp35-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
[pipenv.exceptions.InstallError]: Collecting pydantic==1.10.5 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 64))
[pipenv.exceptions.InstallError]:   Using cached pydantic-1.10.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
[pipenv.exceptions.InstallError]: Collecting pygithub==1.58.0 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 65))
[pipenv.exceptions.InstallError]:   Using cached PyGithub-1.58.0-py3-none-any.whl (312 kB)
[pipenv.exceptions.InstallError]: Collecting pyicu==2.10.2 (from -r /tmp/pipenv-9jjw17w2-requirements/pipenv-qzhrouub-hashed-reqs.txt (line 66))
[pipenv.exceptions.InstallError]:   Using cached PyICU-2.10.2.tar.gz (255 kB)
[pipenv.exceptions.InstallError]:   Installing build dependencies: started
[pipenv.exceptions.InstallError]:   Installing build dependencies: finished with status 'done'
[pipenv.exceptions.InstallError]:   Getting requirements to build wheel: started
[pipenv.exceptions.InstallError]:   Getting requirements to build wheel: finished with status 'error'
[pipenv.exceptions.InstallError]: error: subprocess-exited-with-error
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   × Getting requirements to build wheel did not run successfully.
[pipenv.exceptions.InstallError]:   │ exit code: 1
[pipenv.exceptions.InstallError]:   ╰─> [64 lines of output]
[pipenv.exceptions.InstallError]:       (running 'icu-config --version')
[pipenv.exceptions.InstallError]:       (running 'pkg-config --modversion icu-i18n')
[pipenv.exceptions.InstallError]:       Traceback (most recent call last):
[pipenv.exceptions.InstallError]:         File "<string>", line 89, in <module>
[pipenv.exceptions.InstallError]:         File "<frozen os>", line 679, in __getitem__
[pipenv.exceptions.InstallError]:       KeyError: 'ICU_VERSION'
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       During handling of the above exception, another exception occurred:
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       Traceback (most recent call last):
[pipenv.exceptions.InstallError]:         File "<string>", line 92, in <module>
[pipenv.exceptions.InstallError]:         File "<string>", line 19, in check_output
[pipenv.exceptions.InstallError]:         File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
[pipenv.exceptions.InstallError]:           return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
[pipenv.exceptions.InstallError]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pipenv.exceptions.InstallError]:         File "/usr/lib/python3.11/subprocess.py", line 548, in run
[pipenv.exceptions.InstallError]:           with Popen(*popenargs, **kwargs) as process:
[pipenv.exceptions.InstallError]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pipenv.exceptions.InstallError]:         File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
[pipenv.exceptions.InstallError]:           self._execute_child(args, executable, preexec_fn, close_fds,
[pipenv.exceptions.InstallError]:         File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
[pipenv.exceptions.InstallError]:           raise child_exception_type(errno_num, err_msg, err_filename)
[pipenv.exceptions.InstallError]:       FileNotFoundError: [Errno 2] No such file or directory: 'icu-config'
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       During handling of the above exception, another exception occurred:
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       Traceback (most recent call last):
[pipenv.exceptions.InstallError]:         File "<string>", line 96, in <module>
[pipenv.exceptions.InstallError]:         File "<string>", line 19, in check_output
[pipenv.exceptions.InstallError]:         File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
[pipenv.exceptions.InstallError]:           return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
[pipenv.exceptions.InstallError]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pipenv.exceptions.InstallError]:         File "/usr/lib/python3.11/subprocess.py", line 548, in run
[pipenv.exceptions.InstallError]:           with Popen(*popenargs, **kwargs) as process:
[pipenv.exceptions.InstallError]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pipenv.exceptions.InstallError]:         File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
[pipenv.exceptions.InstallError]:           self._execute_child(args, executable, preexec_fn, close_fds,
[pipenv.exceptions.InstallError]:         File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
[pipenv.exceptions.InstallError]:           raise child_exception_type(errno_num, err_msg, err_filename)
[pipenv.exceptions.InstallError]:       FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config'
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       During handling of the above exception, another exception occurred:
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       Traceback (most recent call last):
[pipenv.exceptions.InstallError]:         File "/usr/lib/python3/dist-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
[pipenv.exceptions.InstallError]:           main()
[pipenv.exceptions.InstallError]:         File "/usr/lib/python3/dist-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
[pipenv.exceptions.InstallError]:           json_out['return_val'] = hook(**hook_input['kwargs'])
[pipenv.exceptions.InstallError]:                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pipenv.exceptions.InstallError]:         File "/usr/lib/python3/dist-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
[pipenv.exceptions.InstallError]:           return hook(config_settings)
[pipenv.exceptions.InstallError]:                  ^^^^^^^^^^^^^^^^^^^^^
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-_vbb_o3q/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
[pipenv.exceptions.InstallError]:           return self._get_build_requires(config_settings, requirements=['wheel'])
[pipenv.exceptions.InstallError]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-_vbb_o3q/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
[pipenv.exceptions.InstallError]:           self.run_setup()
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-_vbb_o3q/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
[pipenv.exceptions.InstallError]:           exec(code, locals())
[pipenv.exceptions.InstallError]:         File "<string>", line 99, in <module>
[pipenv.exceptions.InstallError]:       RuntimeError:
[pipenv.exceptions.InstallError]:       Please install pkg-config on your system or set the ICU_VERSION environment
[pipenv.exceptions.InstallError]:       variable to the version of ICU you have installed.
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       [end of output]
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.
[pipenv.exceptions.InstallError]: error: subprocess-exited-with-error
[pipenv.exceptions.InstallError]: 
[pipenv.exceptions.InstallError]: × Getting requirements to build wheel did not run successfully.
[pipenv.exceptions.InstallError]: │ exit code: 1
[pipenv.exceptions.InstallError]: ╰─> See above for output.
[pipenv.exceptions.InstallError]: 
[pipenv.exceptions.InstallError]: note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Couldn't install package: {}
 Package installation failed...
/usr/lib/python3.11/subprocess.py:1127: ResourceWarning: subprocess 221942 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=4 encoding='utf-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=7 encoding='utf-8'>

Next, after installing the dependencies separately, I still get the same error where "SynchronizedLRUDict" object has no attribute value.

**Comment by codders** [comment]
Yup. You have some missing platform dependencies that the python libraries
need for their build.

Try install libicu-dev, python3-dev and pkgconfig.

Thanks,

Arthur

jcpentester ***@***.***> schrieb am Di., 19. Sept. 2023,
09:41:

**Comment by jcpentester** [comment]
I'll close this issue and will try with a new fresh Kali Linux build. I'm not certain which part/library is causing the error even after following your advice. Appreciate the help alot Codders.
